package mcserver

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf16"
)

// Properties — содержимое server.properties.
type Properties map[string]string

// SecureDefaults возвращает безопасный базовый набор настроек.
//
// Три значения здесь принципиальны:
//
//   - online-mode: в offline-режиме подключиться под ником администратора
//     может кто угодно, поэтому значение приходит из конфига явным
//     параметром, а не берётся из карты properties;
//   - enable-rcon=false: RCON передаёт пароль открытым текстом;
//   - enable-query=false: query работает по UDP и пригоден для усиления
//     DDoS-атак.
//
// Отключать их пользователь может сам, но осознанно и явно.
func SecureDefaults(port int, onlineMode bool) Properties {
	return Properties{
		"server-port":               strconv.Itoa(port),
		"online-mode":               strconv.FormatBool(onlineMode),
		"enable-rcon":               "false",
		"enable-query":              "false",
		"enforce-secure-profile":    "true",
		"prevent-proxy-connections": "false",
		"white-list":                "false",
		"spawn-protection":          "16",
		"max-players":               "20",
		"difficulty":                "normal",
		"gamemode":                  "survival",
		"view-distance":             "10",
		"simulation-distance":       "10",
		"motd":                      "Сервер собран с помощью izba",
	}
}

// Merge накладывает пользовательские значения поверх базовых.
//
// Ключи online-mode, enable-rcon и enable-query переопределяются как и любые
// другие: запрещать их на уровне конфига было бы неуважением к пользователю.
// Вместо запрета выдаётся предупреждение при аудите.
func (p Properties) Merge(user map[string]string) Properties {
	out := make(Properties, len(p)+len(user))
	for k, v := range p {
		out[k] = v
	}
	for k, v := range user {
		out[strings.ToLower(strings.TrimSpace(k))] = v
	}
	return out
}

// escapeValue экранирует значение по правилам java.util.Properties.
//
// Файл читается как ISO-8859-1, поэтому любой символ вне ASCII записывается
// как \uXXXX. Без этого кириллический MOTD превратится в мусор.
func escapeValue(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 128 && (unicode.IsPrint(r) || r == ' ') {
				b.WriteRune(r)
				continue
			}
			// Java ожидает escape-последовательности в кодировке UTF-16,
			// поэтому символы за пределами BMP (эмодзи в том числе)
			// записываются суррогатной парой, а не пятизначным \u.
			for _, u := range utf16.Encode([]rune{r}) {
				b.WriteString(fmt.Sprintf(`\u%04X`, u))
			}
		}
	}
	return b.String()
}

// unescapeValue выполняет обратное преобразование при чтении файла,
// собирая суррогатные пары обратно в один символ.
func unescapeValue(s string) string {
	var units []uint16
	var b strings.Builder
	flush := func() {
		if len(units) > 0 {
			b.WriteString(string(utf16.Decode(units)))
			units = units[:0]
		}
	}
	runes := []rune(s)
	for i := 0; i < len(runes); i++ {
		if runes[i] != '\\' || i+1 >= len(runes) {
			flush()
			b.WriteRune(runes[i])
			continue
		}
		i++
		switch runes[i] {
		case 'n':
			flush()
			b.WriteRune('\n')
		case 'r':
			flush()
			b.WriteRune('\r')
		case 't':
			flush()
			b.WriteRune('\t')
		case '\\':
			flush()
			b.WriteRune('\\')
		case 'u':
			if i+4 < len(runes) {
				if n, err := strconv.ParseUint(string(runes[i+1:i+5]), 16, 16); err == nil {
					units = append(units, uint16(n))
					i += 4
					continue
				}
			}
			flush()
			b.WriteRune('u')
		default:
			flush()
			b.WriteRune(runes[i])
		}
	}
	flush()
	return b.String()
}

// WriteProperties сохраняет файл с отсортированными ключами, чтобы
// последовательные записи давали одинаковый результат.
func WriteProperties(path string, p Properties) error {
	keys := make([]string, 0, len(p))
	for k := range p {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	// Комментарии пишутся на ASCII намеренно: Java читает этот файл как
	// ISO-8859-1, и кириллица в них превратилась бы в нечитаемый набор
	// символов при первом же сохранении сервером.
	b.WriteString("#Minecraft server properties\n")
	b.WriteString("#Generated by izba. Safe to edit by hand:\n")
	b.WriteString("#izba never overwrites an existing server.properties.\n")
	for _, k := range keys {
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(escapeValue(p[k]))
		b.WriteByte('\n')
	}
	return os.WriteFile(path, []byte(b.String()), 0o600)
}

// ReadProperties читает существующий файл.
func ReadProperties(path string) (Properties, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	p := Properties{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "!") {
			continue
		}
		idx := strings.IndexAny(line, "=:")
		if idx < 0 {
			continue
		}
		key := strings.ToLower(strings.TrimSpace(line[:idx]))
		val := unescapeValue(strings.TrimSpace(line[idx+1:]))
		p[key] = val
	}
	return p, sc.Err()
}

// AuditProperties ищет в настройках то, что открывает сервер наружу.
//
// Функция ничего не исправляет: молча менять конфиг, который пользователь
// правил руками, хуже, чем предупредить.
//
// offlineAcknowledged означает, что отключение аутентификации прописано в
// izba.toml, то есть является осознанным выбором. Без этого признака
// online-mode=false в файле — регрессия безопасности: кто-то правил
// server.properties мимо конфига, и запуск нужно остановить.
func AuditProperties(p Properties, offlineAcknowledged bool) []Finding {
	var out []Finding

	if strings.EqualFold(p["online-mode"], "false") {
		if offlineAcknowledged {
			out = append(out, Finding{
				Level:   LevelWarn,
				Message: "online-mode=false: аутентификация Mojang отключена (задано в izba.toml)",
				Hint: "Любой игрок может зайти под чужим ником, включая ник администратора. " +
					"Обязательно включите белый список (white-list) и не открывайте порт в интернет",
			})
		} else {
			out = append(out, Finding{
				Level:   LevelError,
				Message: "в server.properties стоит online-mode=false, а izba.toml этого не требует",
				Hint: "Аутентификация отключена мимо конфига. Либо верните online-mode=true в " +
					"server.properties, либо пропишите server.online_mode = false в izba.toml, " +
					"подтвердив, что это осознанное решение",
			})
		}
	}

	if strings.EqualFold(p["enable-rcon"], "true") {
		pass := p["rcon.password"]
		switch {
		case pass == "":
			out = append(out, Finding{
				Level:   LevelError,
				Message: "RCON включён с пустым паролем",
				Hint:    "Задайте rcon.password или отключите RCON",
			})
		case len(pass) < 16:
			out = append(out, Finding{
				Level:   LevelWarn,
				Message: "пароль RCON короче 16 символов",
				Hint:    "RCON передаёт пароль открытым текстом, короткий пароль подбирается быстро",
			})
		}
		out = append(out, Finding{
			Level:   LevelWarn,
			Message: "RCON включён",
			Hint: "Убедитесь, что порт RCON не доступен из интернета: протокол не шифруется. " +
				"Безопаснее слушать только 127.0.0.1 и ходить через SSH-туннель",
		})
	}

	if strings.EqualFold(p["enable-query"], "true") {
		out = append(out, Finding{
			Level:   LevelWarn,
			Message: "query-протокол включён",
			Hint:    "Он работает по UDP и может использоваться для усиления DDoS-атак",
		})
	}

	return out
}
